<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2ff55c59d1e5d9aa59b47d565ea028e2
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'Violin\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Violin\\' => 
        array (
            0 => __DIR__ . '/..' . '/alexgarrett/violin/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2ff55c59d1e5d9aa59b47d565ea028e2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2ff55c59d1e5d9aa59b47d565ea028e2::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
